BilBasarEgitim/Controllers/AdminDocumentController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BilBasarEgitim.App_Start;
using BilBasarEgitim.Models.Dtos;
using BilBasarEgitim.Services;

namespace BilBasarEgitim.Controllers
{
    [CustomActionFilter]
    public class AdminDocumentController : Controller
    {
        private readonly DocumentService _documentService = new DocumentService();
        // GET: AdminDocument
        public ActionResult Index()
        {

            var model = _documentService.GetAll();
            Response.Cache.SetNoStore();
            return View(model);
           
           
        }
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(DocumentAddDto dto)
        {
            var result = _documentService.Add(dto, dto.File);
            Response.Cache.SetNoStore();
            return Content(result);
        }

        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            _documentService.Delete(id);
            Response.Cache.SetNoStore();
            return RedirectToAction("Index");

        }
    }
}

BilBasarEgitim/Views/AdminDocument/Add.cshtml
@model BilBasarEgitim.Models.Dtos.DocumentAddDto
@{
    ViewBag.Title = "Döküman Yükle";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}
<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); margin: 10px;">
        <div class="modal-content">
            <div class="modal-body" id="errorModalMessage" style="margin: 20px;">
                <!-- Hata mesajı burada görüntülenecek -->
            </div>
        </div>
    </div>
</div>
<main id="main" class="main">

    <section class="section">
        <div class="row">
            
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">
                        
                        <h5 class="card-title mt-4">Döküman Yükleme</h5>
                        @using (Html.BeginForm("Add", "AdminDocument", FormMethod.Post, new { id="document-upload", enctype = "multipart/form-data" }))
                        {
                            <div class="row g-3">
                                <!-- Vertical Form -->
                               
                                    <div class="col-12 row mt-4">
                                        <label for="inputNanme4" class=" col-sm-2 form-label">Döküman Açıklaması</label>
                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" name="Description" id="description">
                                            <span class="error-message" id="description-error"></span>
                                        </div>
                                        
                                    </div>
                                <div class="row mt-4">
                                    <label for="inputNumber" class="col-sm-2 col-form-label">Döküman Yükle</label>
                                    <div class="col-sm-10">
                                        <input class="form-control" name="document" type="file" id="fileInput" accept=".pdf,.doc,.docx" required>
                                        <span class="error-message" id="fileInput-error"></span>
                                    </div>
                                </div>
                                <div>
                                    <input type="hidden" name="AdminId" value="@Guid.Parse(Session["Id"].ToString())" />
                                </div>
                                <div class="text-center mb-4">
                                        <button type="submit" class="btn btn-primary">Yayınla</button>
                                        <button type="reset" class="btn btn-secondary">Temizle</button>
                                    </div>
                            </div>
                        }
                       

                    </div>
                </div>

               

               

            </div>
        </div>
    </section>

</main><!-- End #main -->

BilBasarEgitim/Views/AdminDocument/Index.cshtml
@model List<BilBasarEgitim.Models.Dtos.DocumentPreviewDto>
@{
    ViewBag.Title = "Dökümanlar";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<main id="main" class="main">

    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <div class="col-md-12 text-right mb-3">
                    <a href="/Admin/Dokumanlar/Yukle" class="btn btn-primary">Döküman Yükle</a>
                </div>
                <div class="card">

                    <div class="card-body">
                        <h5 class="card-title">Dökümanlar</h5>
                        <!-- Table with stripped rows -->
                        <table class="table datatable">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Döküman</th>
                                <th scope="col">Açıklama</th>
                                <th scope="col">Yükleme Tarihi</th>
                                <th scope="col">Sil</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if (Model != null)
                            {
                                int i = 1;

                                foreach (var item in Model)
                                {
                                    <tr>
                                        <th scope="row">@i</th>
                                        <td>@item.Description</td>
                                        <td><a href="/Upload/Documents/@item.DocumentUrl">@item.DocumentUrl</a></td>
                                        <td>@item.CreateDate</td>
                                        <td>
                                            <a class="btn btn-danger" href="/Admin/Dokumanlar/Sill/@item.Id">Sil</a>
                                        </td>
                                    </tr>
                                    i++;
                                }
                            }


                            </tbody>
                        </table>

                    </div>
                </div>

            </div>
        </div>
    </section>

</main>