BilBasarEgitim/Controllers/AdminGalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BilBasarEgitim.App_Start;
using BilBasarEgitim.Models.Dtos.Gallery;
using BilBasarEgitim.Services;

namespace BilBasarEgitim.Controllers
{
    [CustomActionFilter]
    public class AdminGalleryController : Controller
    {
        private readonly GalleryService galleryService = new GalleryService();
        // GET: AdminGallery
        public ActionResult Index()
        {
            var model = galleryService.GetAllNotDelete();
            Response.Cache.SetNoStore();
            return View(model);
        }

        public ActionResult Upload()
        {
            Response.Cache.SetNoStore();
            return View();
        }

        [HttpPost]
        public string Upload(GalleryAddDto dto)
        {
            Response.Cache.SetNoStore();
            var result = galleryService.Add(dto);
            return result;
        }

        [HttpGet]
        public ActionResult UpdateRelease(Guid Id, bool check)
        {
            galleryService.Update(Id, check);
            Response.Cache.SetNoStore();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(Guid Id)
        {
            galleryService.Delete(Id);
            Response.Cache.SetNoStore();
            return RedirectToAction("Index");
        }

        public ActionResult Placement()
        {
            var dtos = galleryService.GetAllForPlacement();
            Response.Cache.SetNoStore();
            return View(dtos);
        }
        [HttpPost]
        public ActionResult Placement(GalleryPlacementUpdateDto dtos)
        {
            galleryService.GalleryPlacementUpdate(dtos);
            Response.Cache.SetNoStore();
            return RedirectToAction("Placement");
        }
    }
}

BilBasarEgitim/Views/AdminGallery/Index.cshtml
@model List<BilBasarEgitim.Models.Dtos.Gallery.GalleryForAdminDto>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<main class="main" id="main">

    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <div class="col-md-12 mb-3 row">
                   
                    <div class="col-md-6 ">
                        <a href="/admin/galeri/duzenle" class="btn btn-primary">Galeri Sırası Düzenle</a>
                    </div>
                    <div class=" col-md-6 text-right">
                        <a href="/admin/galeri/yukle" class="btn btn-primary">Galeri Ekle</a>
                    </div>
                    
                </div>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Galeri</h5>
                        <!-- Table with stripped rows -->
                        <table class="table datatable">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Resim</th>
                                    <th scope="col">Açıklama</th>
                                    <th scope="col">Yayında Mı?</th>
                                    <th scope="col">Yükleme Tarihi</th>
                                    <th scope="col">Yayınla</th>
                                    <th scope="col">Yayından Kaldır</th>
                                    <th scope="col">Sil</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model == null)
                                {


                                }
                                else
                                {

                                    int i = 1;
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <th scope="row">@i</th>
                                            <td><a href="~/Upload/Images/Gallery/@item.ImageUrl"><img src="~/Upload/Images/Gallery/@item.ImageUrl" style="max-height: 300px; max-width: 300px;" /></a></td>
                                            <td>@item.Description</td>
                                            <td>@item.Check</td>
                                            <td>@item.CreateDate</td>
                                            <td><a href="@Url.Action("UpdateRelease","AdminGallery",new {id=item.Id, check = true})" class="btn btn-success">Yayınla</a></td>
                                            <td><a href="@Url.Action("UpdateRelease","AdminGallery", new {id= item.Id,check= false})" class="btn btn-danger">Yayından Kaldır</a></td>
                                            <td><a href="@Url.Action("Delete","AdminGallery", new {id = item.Id})" class="btn btn-danger">Sil</a></td>

                                        </tr>
                                        i++;
                                    }
                                }



                            </tbody>
                        </table>

                    </div>
                </div>

            </div>
        </div>
    </section>
</main>

BilBasarEgitim/Views/AdminGallery/Placement.cshtml
@using BilBasarEgitim.Models.Entities
@model BilBasarEgitim.Models.Dtos.Gallery.GalleryPlacementWithUiDto
@{
    ViewBag.Title = "Palacement";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<main class="main" id="main">

    @using (Html.BeginForm("Placement", "AdminGallery", FormMethod.Post))
    {
        <input type="submit" value="Sıralamayı Güncelle"  class="btn btn-primary"/>
        <section class="section">
            @{
                int m = 0;
            }
            @for (int i = 0; i < Model.GalleryUi.LineNumber; i++)
            {

                if (i == Model.GalleryUi.LineNumber - 1)
                {
                    <div class="container row col-12 justify-content-center">
                        @for (int j = 0; j < Model.GalleryUi.DataNumInLastLine; j++)
                        {
                            <div class="card col-sm-2 me-5 " style="@(Model.GalleryPlacementDtos[m].Check==false ? "opacity:0.5;" : "")">
                                <div class="card-body">
                                    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
                                        <div class="carousel-inner">
                                            <div class="carousel-item active">
                                                <img src="~/Upload/Images/Gallery/@Model.GalleryPlacementDtos[m].ImageUrl" class="d-block w-100">

                                            </div>
                                        </div>
                                    </div>
                                    <h5 class="card-title">@Model.GalleryPlacementDtos[m].Description</h5>
                                    <input type="number" name="PlacementUpdate" value="@Model.GalleryPlacementDtos[m].Placement" style="width: 100%" />
                                    <input type="hidden" name="GalleryId" value="@Model.GalleryPlacementDtos[m].Id" />
                                </div>
                            </div>
                            m++;
                        }
                    </div>
                }
                else
                {
                    <div class="container row col-12 justify-content-center">
                        @for (int k = 0; k < 4; k++)
                        {
                            <div class="card col-sm-2 me-5 " style="opacity:  @(Model.GalleryPlacementDtos[m].Check==false ? "0.5" : "1")">
                                <div class="card-body">
                                    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
                                        <div class="carousel-inner">
                                            <div class="carousel-item active">
                                                <img src="~/Upload/Images/Gallery/@Model.GalleryPlacementDtos[m].ImageUrl" class="d-block w-100">

                                            </div>
                                        </div>
                                    </div>
                                    <h5 class="card-title">@Model.GalleryPlacementDtos[m].Description</h5>
                                    <input type="number" name="PlacementUpdate" value="@Model.GalleryPlacementDtos[m].Placement" style="width: 100%" />
                                    <input type="hidden" name="GalleryId" value="@Model.GalleryPlacementDtos[m].Id" />
                                </div>
                            </div>
                            m++;
                        }
                    </div>
                }



            }


        </section>

    }




</main>

BilBasarEgitim/Views/AdminGallery/Upload.cshtml
@model BilBasarEgitim.Models.Dtos.Gallery.GalleryAddDto
@{
    ViewBag.Title = "Upload";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); margin: 10px;">
        <div class="modal-content">
            <div class="modal-body" id="errorModalMessage" style="margin: 20px;">
                <!-- Hata mesajı burada görüntülenecek -->
            </div>
        </div>
    </div>
</div>
<main class="main" id="main">
    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Galeri Yükleme</h5>


                        <form action="/admin/galeri" method="post" id="gallery-upload" enctype="multipart/form-data">
                            <div class="row mb-3">
                                <label for="inputNumber" class="col-sm-2 col-form-label">Resim Yükle</label>
                                <div class="col-sm-10">
                                    <input type="file" id="fileInput" name="ImageUrl" accept="image/*">
                                    <span class="error-message" id="fileInput-error"></span>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2">Önizleme</label>
                                <img class="col-sm-10" id="imagePreview" src="#" alt="Image Preview" style="max-width: 700px; max-height: 700px; display: none;">
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label">Açıklama</label>
                                <div class="col-sm-10">
                                    <input type="text" name="Description" id="description" style="width: 100%;">
                                    <span class="error-message" id="description-error"></span>

                                </div>
                            </div>
                            <div class="row mb-3">
                                <legend class="col-form-label col-sm-2 pt-0">Resim hemen yayınlansın mı?</legend>
                                <div class="col-sm-10">

                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" id="gridCheck1" name="Check" value="true" checked>
                                    </div>

                                </div>
                            </div>
                            <input type="hidden" name="AdminId" value="@Guid.Parse(Session["Id"].ToString())" />
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label"></label>
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-primary">Kaydet</button>
                                </div>
                            </div>
                        </form>




                    </div>
                </div>

            </div>
        </div>
    </section>
</main>