BilBasarEgitim/Controllers/AdminAcademicStaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BilBasarEgitim.App_Start;
using BilBasarEgitim.Models.Dtos.AcademicStaff;
using BilBasarEgitim.Services;

namespace BilBasarEgitim.Controllers
{
    [CustomActionFilter]
    public class AdminAcademicStaffController : Controller
    {
        private readonly AcademicStaffService academic = new AcademicStaffService();
        // GET: AdminAcademicStaff
        public ActionResult Index()
        {
            var model = academic.GetAll();
            Response.Cache.SetNoStore();
            return View(model);
        }

        public ActionResult Upload()
        {
            Response.Cache.SetNoStore();
            return View();
        }

        [HttpPost]
        public ActionResult Upload(AcademicStaffAddDto dto)
        {
            
            var result = academic.Add(dto);
            Response.Cache.SetNoStore();
            return Content(result);
        }

        public ActionResult Update(Guid id)
        {
            var model = academic.GetById(id);
            return View(model);
        }

        [HttpPost]
        public string Update(AcademicStaffUpdateDto dto)
        {
            var result = academic.Update(dto);
            Response.Cache.SetNoStore();
            return result;
        }

        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            academic.Delete(id);
            Response.Cache.SetNoStore();
            return RedirectToActionPermanent("Index");
        }

        [HttpGet]
        public ActionResult UpdateRelease(Guid id, bool check)
        {
            academic.UpdateRelease(id, check);
            Response.Cache.SetNoStore();
            return RedirectToAction("Index");
        }

    }
}

BilBasarEgitim/Views/AdminAcademicStaff/Index.cshtml
@model List<BilBasarEgitim.Models.Dtos.AcademicStaff.AcademicStaffPreviewForAdminDto>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<main class="main" id="main">

    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <div class="col-md-12 text-right mb-3">
                    <a href="/admin/akademik-kadro/yukle" class="btn btn-primary">Eğitmen Kaydet</a>
                </div>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Eğitmenler</h5>
                        <!-- Table with stripped rows -->
                        <table class="table datatable">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Ad Soyad</th>
                                    <th scope="col">Eğitim Dalı</th>
                                    <th scope="col">Görünüyor Mu?</th>
                                    <th scope="col">Kayıt Tarihi</th>
                                    <th scope="col">Yayınla</th>
                                    <th scope="col">Yayından Kaldır</th>
                                    <th scope="col">Düzenle</th>
                                    <th scope="col">Sil</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model == null)
                                {


                                }
                                else
                                {

                                    int i = 1;
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <th scope="row">@i</th>
                                            <td>@item.FullName</td>
                                            <td>@item.EdicatorField</td>
                                            <td>@item.Check</td>
                                            <td>@item.CreateDate</td>
                                            <td><a href="@Url.Action("UpdateRelease","AdminAcademicStaff",new {id=item.Id, check = true})" class="btn btn-success">Göster</a></td>
                                            <td><a href="@Url.Action("UpdateRelease","AdminAcademicStaff", new {id= item.Id,check= false})" class="btn btn-danger">Gizle</a></td>
                                            <td><a href="@Url.Action("Update","AdminAcademicStaff", new {id= item.Id})" class="btn btn-danger">Düzenle</a></td>
                                            <td><a href="@Url.Action("Delete","AdminAcademicStaff", new {id = item.Id})" class="btn btn-danger">Sil</a></td>

                                        </tr>
                                        i++;
                                    }
                                }



                            </tbody>
                        </table>

                    </div>
                </div>

            </div>
        </div>
    </section>
</main>

BilBasarEgitim/Views/AdminAcademicStaff/Update.cshtml
@model BilBasarEgitim.Models.Dtos.AcademicStaff.AcademicStaffUpdateDto
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); margin: 10px;">
        <div class="modal-content">
            <div class="modal-body" id="errorModalMessage" style="margin: 20px;">
                <!-- Hata mesajı burada görüntülenecek -->
            </div>
        </div>
    </div>
</div>
<main class="main" id="main">
    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Eğitmen Bilgisi Güncelle</h5>
                        <div class="row mb-3">
                            <label class="col-sm-2">Mevcut Resim</label>
                            <img class="col-sm-10" src="~/Upload/Images/AcademicStaff/@Model.ImageUrl" style="max-width: 700px; max-height: 700px;">
                        </div>
                        <hr style="border-width: 5px; display: block" />
                        <form action="/admin/akademik-kadro/guncelle" method="post" id="academic-staff-update" enctype="multipart/form-data">

                            <div class="row mb-3">
                                <label for="inputNumber" class="col-sm-2 col-form-label">Resim Değiştir</label>
                                <div class="col-sm-10">
                                    <input type="file" id="fileInput" name="file" accept="image/*">
                                    <span class="error-message" id="fileInput-error"></span>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label class="col-sm-2">Önizleme</label>
                                <img class="col-sm-10" id="imagePreview" src="#" alt="Image Preview" style="max-width: 700px; max-height: 700px; display: none;">
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label">Ad</label>
                                <div class="col-sm-10">
                                    <input type="text" name="name" id="yourName" style="width: 50%" value="@Model.Name">
                                    <span class="error-message" id="name-error"></span>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label">Soyad</label>
                                <div class="col-sm-10">
                                    <input type="text" name="surname" id="yourSurname" style="width: 50%" value="@Model.SurName">
                                    <span class="error-message" id="surname-error"></span>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label">Eğitim Dalı</label>
                                <div class="col-sm-10">
                                    <input type="text" name="EducatorField" id="educatorfield" style="width: 50%" value="@Model.EducatorField">
                                    <span class="error-message" id="educator-error"></span>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label">FaceBook</label>
                                <div class="col-sm-10">
                                    <input type="text" name="FacebookUrl" style="width: 50%" value="@Model.FaceBookUrl">

                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label">Twitter</label>
                                <div class="col-sm-10">
                                    <input type="text" name="TwitterUrl" style="width: 50%" value="@Model.TwitterUrl">

                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label">Instagram</label>
                                <div class="col-sm-10">
                                    <input type="text" name="InstagramUrl" style="width: 50%" value="@Model.InstagramUrl">

                                </div>
                            </div>

                            <input type="hidden" name="Id" value="@Model.Id" />
                            <input type="hidden" name="ImageUrl" value="@Model.ImageUrl" />
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label"></label>
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-primary">Kaydet</button>
                                </div>
                            </div>
                        </form>




                    </div>
                </div>

            </div>
        </div>
    </section>
</main>

BilBasarEgitim/Views/AdminAcademicStaff/Upload.cshtml
@{
    ViewBag.Title = "Upload";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); margin: 10px;">
        <div class="modal-content">
            <div class="modal-body" id="errorModalMessage" style="margin: 20px;">
                <!-- Hata mesajı burada görüntülenecek -->
            </div>
        </div>
    </div>
</div>
<main class="main" id="main">
    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Eğitmen Yükleme</h5>


                        <form action="/admin/akademik-kadro/yukle" method="post" id="academic-staff-upload" enctype="multipart/form-data">
                            <div class="row mb-3">
                                <label for="inputNumber" class="col-sm-2 col-form-label">Resim Yükle</label>
                                <div class="col-sm-10">
                                    <input type="file" id="fileInput" name="file" accept="image/*">
                                    <span class="error-message" id="fileInput-error"></span>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label class="col-sm-2">Önizleme</label>
                                <img class="col-sm-10" id="imagePreview" src="#" alt="Image Preview" style="max-width: 700px; max-height: 700px; display: none;">
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label">Ad</label>
                                <div class="col-sm-10">
                                    <input type="text" name="name" id="yourName" style="width: 50%">
                                    <span class="error-message" id="name-error"></span>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label">Soyad</label>
                                <div class="col-sm-10">
                                    <input type="text" name="surname" id="yourSurname"style="width: 50%">
                                    <span class="error-message" id="surname-error"></span>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label">Eğitim Dalı</label>
                                <div class="col-sm-10">
                                    <input type="text" name="EducatorField" id="educatorfield" style="width: 50%">
                                    <span class="error-message" id="educator-error"></span>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label">FaceBook</label>
                                <div class="col-sm-10">
                                    <input type="text" name="FacebookUrl" style="width: 50%">

                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label">Twitter</label>
                                <div class="col-sm-10">
                                    <input type="text" name="TwitterUrl" style="width: 50%">

                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label">Instagram</label>
                                <div class="col-sm-10">
                                    <input type="text" name="InstagramUrl" style="width: 50%">

                                </div>
                            </div>

                            <div class="row mb-3">
                                <legend class="col-form-label col-sm-2 pt-0">Eğitmen hemen yayınlansın mı?</legend>
                                <div class="col-sm-10">

                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" id="gridCheck1" name="Check" value="true" checked>
                                    </div>

                                </div>
                            </div>
                            <input type="hidden" name="AdminId" value="@Guid.Parse(Session["Id"].ToString())" />
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label"></label>
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-primary">Kaydet</button>
                                </div>
                            </div>
                        </form>




                    </div>
                </div>

            </div>
        </div>
    </section>
</main>